# Generated by Django 3.0.7 on 2020-06-21 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tvrtke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_tvrtke', models.CharField(max_length=100)),
                ('struka', models.CharField(max_length=100)),
                ('naziv_tvrtke_za_praksu', models.CharField(max_length=100)),
                ('opis_zadataka', models.TextField()),
                ('datum_objave', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
